name: pocofino
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  auth_repository:
    path: packages/auth_repository
  bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  cloud_firestore: ^5.2.0
  database_api:
    path: packages/database_api
  equatable: ^2.0.5
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  fluttertoast: ^8.2.6
  flutter_bloc: ^8.1.4
  flutter_form_builder: ^9.3.0
  flutter_map: ^7.0.2
  flutter_native_splash: ^2.3.10
  form_builder_validators: ^10.0.1
  get_it: ^7.6.7
  google_sign_in: ^6.2.1
  go_router: ^14.2.0
  product_repository:
    path: packages/product_repository
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.9

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bely Display
      fonts:
        - asset: assets/fonts/Bely-Display-W00-Regular.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Black.otf
        - asset: assets/fonts/AvenirLTStd-Book.otf
        - asset: assets/fonts/AvenirLTStd-Roman.otf
   
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
